package raccoonman.reterraforged.mixin;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

import net.minecraft.resources.RegistryDataLoader;
import net.minecraft.server.packs.resources.Resource;
import raccoonman.reterraforged.data.PresetPacks;

@Mixin(RegistryDataLoader.class)
class MixinRegistryDataLoader {

	/*
	 * Vanilla treats worldgen from any pack that isn't built in as experimental and asks for confirmation when such
	 * a world is created. A ReTerraForged world's preset pack lives in its datapacks folder like a user pack, but
	 * it's generated by the mod, so treat it as built in.
	 */
	@Redirect(
		method = "loadRegistryContents",
		at = @At(
			value = "INVOKE",
			target = "Lnet/minecraft/server/packs/resources/Resource;isBuiltin()Z"
		),
		require = 1
	)
	private static boolean reterraforged$isBuiltin(Resource resource) {
		return resource.isBuiltin() || PresetPacks.isPresetPack(resource.sourcePackId());
	}
}
