package com.pandaismyname1.ultraterraforged.mixin;

import java.util.Optional;
import java.util.function.Function;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

import com.mojang.serialization.Lifecycle;

import net.minecraft.core.RegistrationInfo;
import net.minecraft.resources.ResourceManagerRegistryLoadTask;
import net.minecraft.server.packs.repository.KnownPack;
import net.minecraft.server.packs.resources.Resource;
import com.pandaismyname1.ultraterraforged.UTFCommon;
import com.pandaismyname1.ultraterraforged.data.PresetPacks;

/*
 * Vanilla treats worldgen from any pack that isn't built in as experimental and asks for confirmation when such a
 * world is created. A UltraTerraForged world's preset pack lives in its datapacks folder like a user pack, but it's
 * generated by the mod, so its entries are registered as stable. It isn't made a known pack: those aren't sent to
 * clients, and the preset's biome changes must be.
 *
 * Each element's registration info is REGISTRATION_INFO_CACHE.apply(resource.knownPackInfo()), in a lambda of load(),
 * the only call of each in the class. The lambda's name is left to the compiler, so the targets are "*": the first
 * redirect marks a preset pack's resources, the second gives them stable registration info.
 */
@Mixin(ResourceManagerRegistryLoadTask.class)
class MixinResourceManagerRegistryLoadTask {
	@Unique
	private static final Optional<KnownPack> ultraterraforged$PRESET_PACK = Optional.of(new KnownPack(UTFCommon.MOD_ID, "preset", "0"));
	@Unique
	private static final RegistrationInfo ultraterraforged$STABLE = new RegistrationInfo(Optional.empty(), Lifecycle.stable());

	@Redirect(
		method = "*",
		at = @At(
			value = "INVOKE",
			target = "Lnet/minecraft/server/packs/resources/Resource;knownPackInfo()Ljava/util/Optional;"
		),
		require = 1
	)
	private Optional<KnownPack> ultraterraforged$knownPackInfo(Resource resource) {
		return PresetPacks.isPresetPack(resource.sourcePackId()) ? ultraterraforged$PRESET_PACK : resource.knownPackInfo();
	}

	@Redirect(
		method = "*",
		at = @At(
			value = "INVOKE",
			target = "Ljava/util/function/Function;apply(Ljava/lang/Object;)Ljava/lang/Object;"
		),
		require = 1
	)
	private Object ultraterraforged$registrationInfo(Function<Object, Object> registrationInfoCache, Object knownPack) {
		return knownPack == ultraterraforged$PRESET_PACK ? ultraterraforged$STABLE : registrationInfoCache.apply(knownPack);
	}
}
