package com.pandaismyname1.ultraterraforged.mixin;

import java.io.IOException;
import java.util.Optional;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

import com.google.gson.JsonElement;
import com.mojang.serialization.Decoder;
import com.mojang.serialization.Lifecycle;

import net.minecraft.core.RegistrationInfo;
import net.minecraft.core.WritableRegistry;
import net.minecraft.resources.RegistryDataLoader;
import net.minecraft.resources.RegistryOps;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.packs.resources.Resource;
import com.pandaismyname1.ultraterraforged.data.PresetPacks;

@Mixin(RegistryDataLoader.class)
class MixinRegistryDataLoader {

	@Shadow
	private static <E> void loadElementFromResource(WritableRegistry<E> registry, Decoder<E> decoder, RegistryOps<JsonElement> ops, ResourceKey<E> key, Resource resource, RegistrationInfo info) throws IOException {
		throw new AssertionError();
	}

	/*
	 * Vanilla treats worldgen from any pack that isn't built in as experimental and asks for confirmation when such
	 * a world is created. A UltraTerraForged world's preset pack lives in its datapacks folder like a user pack, but
	 * it's generated by the mod, so treat it as stable. It isn't made a known pack: those aren't sent to clients, and
	 * the preset's biome changes must be.
	 */
	@Redirect(
		method = "loadContentsFromManager",
		at = @At(
			value = "INVOKE",
			target = "Lnet/minecraft/resources/RegistryDataLoader;loadElementFromResource(Lnet/minecraft/core/WritableRegistry;Lcom/mojang/serialization/Decoder;Lnet/minecraft/resources/RegistryOps;Lnet/minecraft/resources/ResourceKey;Lnet/minecraft/server/packs/resources/Resource;Lnet/minecraft/core/RegistrationInfo;)V"
		),
		require = 1
	)
	private static <E> void ultraterraforged$loadElement(WritableRegistry<E> registry, Decoder<E> decoder, RegistryOps<JsonElement> ops, ResourceKey<E> key, Resource resource, RegistrationInfo info) throws IOException {
		if (PresetPacks.isPresetPack(resource.sourcePackId())) {
			info = new RegistrationInfo(Optional.empty(), Lifecycle.stable());
		}
		loadElementFromResource(registry, decoder, ops, key, resource, info);
	}
}
